import { v } from "convex/values";
import { query } from "./_generated/server";
import type { QueryCtx } from "./_generated/server";
import { requireOrgReadDoc, requireOrgPermission } from "./lib/auth";

/**
 * Reactive "version vector" for the asset DETAIL page (Phase 6 — React Query
 * removal, bucket-B reactive composites). HAND-WRITTEN — NOT generated by
 * scripts/generate-convex-crud.cjs (that script owns convex/assets.ts and would
 * clobber any addition there). Follows the convex/<table>Detail.ts convention
 * established by convex/kitDetail.ts (the keystone).
 *
 * WHY a version vector and not a full reactive composite. The asset detail page
 * (`assets/registry/[id]`) is served by the `getAsset` server action, which
 * composes data Convex CANNOT hold — `scanLogs.scannedBy` is a Better Auth USER
 * (stays in Prisma forever), plus maintenanceRecords / line items / test-tag /
 * cross-domain model+category+supplier joins. Replicating that shape in a Convex
 * query is infeasible AND the exact data-shape-drift footgun CLAUDE.md warns
 * about. So the server action stays BYTE-IDENTICAL and we add only this cheap
 * reactive trigger: the browser subscribes to `version`, and
 * `useReactiveServerQuery` re-runs `getAsset` whenever the vector changes. Convex
 * pushes the new vector to every subscriber over the WebSocket → cross-user
 * reactivity.
 *
 * ★ SCOPE (the silent-staleness contract — see FEATUREDOCS/54 + kitDetail.ts).
 * The vector must be a SUPERSET of the page's existing live-refresh scope without
 * over-reaching. Two facts about THIS branch made the scope analysis short:
 *   1. The SSE realtime system currently emits NOTHING — every `logActivity`
 *      call passes a lowercase `entityType` ("asset", "maintenance", …) but
 *      `mapEntityTypeToEvent` (src/lib/activity-log.ts) switches on PascalCase
 *      ("Asset", "MaintenanceRecord", …). No case matches, so `asset:updated` /
 *      `maintenance:changed` are never fired. Cross-user reactivity for this page
 *      did NOT exist; the vector is therefore a pure, safe ADDITION (a superset),
 *      not a thing that could regress.
 *   2. The only refresh that DID happen was SAME-VIEW (the page's own mutations
 *      and MediaUploader/NotesEditor onChanged → invalidateQueries). That is
 *      preserved on the page by an explicit refetch() in every mutation onSuccess,
 *      independent of this vector.
 *
 * So this vector exists to give the page proper cross-user / cross-tab liveness.
 * It captures the head doc + the page-visible MUTABLE sub-tables that ARE mirrored
 * to Convex:
 *   • asset doc `updatedAt` — every asset-row mutation (status, condition, notes,
 *     location, supplier, custom fields, …) bumps Prisma's @updatedAt, copied by
 *     the mirror. (This benignly over-reaches on warehouse status syncs, which is
 *     fine — more up-to-date, never stale.)
 *   • a CONTENT SIGNATURE over `assetMedia` (the Photos tab — dual-written via
 *     media-mirror.ts). Like kitMedia, a count+max-ts vector would MISS an
 *     in-place `setAssetPrimaryPhoto` (flips isPrimary only, same count/createdAt);
 *     the signature folds in isPrimary/sortOrder/type/fileId/displayName so
 *     add/remove AND in-place edits all move it.
 *   • a signature over `childAssets` (serialized accessories = assets whose
 *     `parentAssetId` is this asset; the Accessories sidebar). Attaching mirrors
 *     the child's parentAssetId, so attach moves the vector.
 *
 * KNOWN GAPS (acceptable — covered by the same-view refetch path, and cross-user
 * liveness here is NEW, not a regression):
 *   • DETACHING an accessory clears `child.parentAssetId` to null, which is a
 *     Convex no-op (the clear-to-null caveat documented in asset-mirror.ts) — the
 *     child stays pointed at this asset in the mirror, so a cross-user detach does
 *     not move the vector. The same-view detach refetches the Prisma source of
 *     truth directly, so the acting user always sees it.
 *   • `assetBulkChildren` (bulk accessories) is in the Convex SCHEMA but is NOT
 *     yet dual-written, so a signature over it would always be empty. It is left
 *     OUT until that table is mirrored; same-view bulk-accessory writes refetch.
 *   • The Maintenance / History tabs are intentionally OUT (their writes never
 *     fired an SSE event that hit this page's key, and maintenance is Prisma-only).
 *
 * Browser-readable: reads the asset doc, enforces org scoping via
 * requireOrgReadDoc (a user token's orgId must match the asset's org), then reads
 * sub-tables by assetId / parentAssetId. Returns only counts/ids/timestamps/flags
 * — no secrets.
 */
export const version = query({
  args: { id: v.string() },
  handler: async (ctx, { id }) => {
    const asset = await ctx.db
      .query("assets")
      .withIndex("by_cuid", (q) => q.eq("id", id))
      .unique();
    await requireOrgReadDoc(ctx, asset);
    if (!asset) return null;

    const [media, children] = await Promise.all([
      ctx.db
        .query("assetMedia")
        .withIndex("by_assetId", (q) => q.eq("assetId", id))
        .collect(),
      ctx.db
        .query("assets")
        .withIndex("by_parentAssetId", (q) => q.eq("parentAssetId", id))
        .collect(),
    ]);

    // Deterministic per-row signatures (sorted, so insertion order can't perturb
    // them). Each folds in the mutable fields the detail view renders, so an
    // in-place edit (e.g. isPrimary) moves the vector — not just adds/removes.
    const mediaSig = media
      .map(
        (m) =>
          `${m.id}:${m.isPrimary ? 1 : 0}:${m.sortOrder ?? ""}:${m.type ?? ""}:${m.fileId}:${m.displayName ?? ""}`,
      )
      .sort()
      .join("|");
    const childSig = children
      .map((c) => `${c.id}:${c.assetTag}`)
      .sort()
      .join("|");

    return {
      asset: asset.updatedAt ?? asset._creationTime,
      media: mediaSig,
      children: childSig,
    };
  },
});

/**
 * BROWSER-facing composite for the ASSET detail page (Phase 2 native reads).
 * Returns everything getAsset needs as RAW docs (asset + model/category/supplier/
 * parent/location, asset & model media + files, child assets + their models, child
 * bulk children + their bulk assets/models, ≤20 usage line items + projects, test-
 * tag, maintenance links + records, model bulk accessories + their bulk
 * assets/models) so the client reconstructs the getAsset shape from ONE live
 * subscription. Gated on requireOrgPermission(asset, read). scanLogs omitted (no
 * page consumer). Returns null when the asset is missing / cross-org.
 */
async function readAssetDetail(ctx: QueryCtx, assetId: string, orgId: string) {
  const asset = await ctx.db.query("assets").withIndex("by_cuid", (q) => q.eq("id", assetId)).unique();
  if (!asset || asset.organizationId !== orgId) return null;

  const uniq = (arr: Array<string | undefined | null>): string[] => [
    ...new Set(arr.filter((x): x is string => !!x)),
  ];
  const pr = <T>(rows: Promise<T | null>[]) => Promise.all(rows);
  const inOrg = <T extends { organizationId?: string | null }>(arr: (T | null)[]) =>
    arr.filter((d): d is T => d !== null && d.organizationId === orgId);

  const [assetMedia, modelMedia, childAssetDocs, childBulkDocs, lineItemsAll, testTags, maintLinks, modelAccessories] =
    await Promise.all([
      ctx.db.query("assetMedia").withIndex("by_assetId", (q) => q.eq("assetId", assetId)).collect(),
      asset.modelId
        ? ctx.db.query("modelMedia").withIndex("by_modelId", (q) => q.eq("modelId", asset.modelId!)).collect()
        : Promise.resolve([]),
      ctx.db.query("assets").withIndex("by_parentAssetId", (q) => q.eq("parentAssetId", assetId)).collect(),
      ctx.db.query("assetBulkChildren").withIndex("by_parentAssetId", (q) => q.eq("parentAssetId", assetId)).collect(),
      ctx.db.query("projectLineItems").withIndex("by_assetId", (q) => q.eq("assetId", assetId)).collect(),
      ctx.db.query("testTagAssets").withIndex("by_assetId", (q) => q.eq("assetId", assetId)).collect(),
      ctx.db.query("maintenanceRecordAssets").withIndex("by_assetId", (q) => q.eq("assetId", assetId)).collect(),
      asset.modelId
        ? ctx.db.query("modelBulkAccessories").withIndex("by_modelId", (q) => q.eq("modelId", asset.modelId!)).collect()
        : Promise.resolve([]),
    ]);

  const [model, supplier, parentAsset, location] = await Promise.all([
    asset.modelId ? ctx.db.query("models").withIndex("by_cuid", (q) => q.eq("id", asset.modelId!)).unique() : Promise.resolve(null),
    asset.supplierId ? ctx.db.query("suppliers").withIndex("by_cuid", (q) => q.eq("id", asset.supplierId!)).unique() : Promise.resolve(null),
    asset.parentAssetId ? ctx.db.query("assets").withIndex("by_cuid", (q) => q.eq("id", asset.parentAssetId!)).unique() : Promise.resolve(null),
    asset.locationId ? ctx.db.query("locations").withIndex("by_cuid", (q) => q.eq("id", asset.locationId!)).unique() : Promise.resolve(null),
  ]);
  const category = model?.categoryId
    ? await ctx.db.query("categories").withIndex("by_cuid", (q) => q.eq("id", model.categoryId!)).unique()
    : null;

  // ≤20 most-recent usage line items (mirror getAsset's sort + slice).
  const lineItems = [...lineItemsAll]
    .sort((a, b) => (b.createdAt ?? 0) - (a.createdAt ?? 0))
    .slice(0, 20)
    .filter((r) => r.organizationId === orgId);

  // Bulk assets referenced by child bulk children + model accessories.
  const refBulkIds = uniq([...childBulkDocs.map((c) => c.bulkAssetId), ...modelAccessories.map((a) => a.bulkAssetId)]);
  const bulkAssets = inOrg(await pr(refBulkIds.map((id) => ctx.db.query("bulkAssets").withIndex("by_cuid", (q) => q.eq("id", id)).unique())));

  // Models referenced by child assets + child-bulk/model-accessory bulk assets.
  const refModelIds = uniq([
    ...childAssetDocs.map((a) => a.modelId),
    ...bulkAssets.map((b) => b.modelId),
  ]);
  const models = inOrg(await pr(refModelIds.map((id) => ctx.db.query("models").withIndex("by_cuid", (q) => q.eq("id", id)).unique())));

  const refProjectIds = uniq(lineItems.map((r) => r.projectId));
  const projects = inOrg(await pr(refProjectIds.map((id) => ctx.db.query("projects").withIndex("by_cuid", (q) => q.eq("id", id)).unique())));

  const refMaintIds = uniq(maintLinks.map((l) => l.maintenanceRecordId));
  const maintenanceRecords = inOrg(await pr(refMaintIds.map((id) => ctx.db.query("maintenanceRecords").withIndex("by_cuid", (q) => q.eq("id", id)).unique())));

  const refFileIds = uniq([...assetMedia.map((m) => m.fileId), ...modelMedia.map((m) => m.fileId)]);
  const files = inOrg(await pr(refFileIds.map((id) => ctx.db.query("fileUploads").withIndex("by_cuid", (q) => q.eq("id", id)).unique())));

  return {
    asset,
    model: model && model.organizationId === orgId ? model : null,
    category: category && category.organizationId === orgId ? category : null,
    supplier: supplier && supplier.organizationId === orgId ? supplier : null,
    parentAsset: parentAsset && parentAsset.organizationId === orgId ? parentAsset : null,
    location: location && location.organizationId === orgId ? location : null,
    assetMedia,
    modelMedia,
    childAssets: childAssetDocs.filter((c) => c.organizationId === orgId),
    childBulkChildren: childBulkDocs.filter((c) => c.organizationId === orgId),
    lineItems,
    testTags,
    maintenanceLinks: maintLinks,
    modelAccessories,
    bulkAssets,
    models,
    projects,
    maintenanceRecords,
    files,
  };
}

export const bundle = query({
  args: { assetId: v.string(), orgId: v.string() },
  handler: async (ctx, { assetId, orgId }) => {
    await requireOrgPermission(ctx, orgId, "asset", "read");
    return readAssetDetail(ctx, assetId, orgId);
  },
});
