import { v } from "convex/values";
import { query } from "./_generated/server";
import type { QueryCtx } from "./_generated/server";
import { requireOrgReadDoc, requireOrgPermission } from "./lib/auth";

/**
 * Reactive "version vector" for the kit DETAIL page (Phase 6 — React Query removal,
 * bucket-B reactive composites). HAND-WRITTEN — NOT generated by
 * scripts/generate-convex-crud.cjs (that script owns convex/kits.ts and would
 * clobber any addition there). Establishes the convex/<table>Detail.ts convention
 * for the other bucket-B detail composites (asset/project/warehouse).
 *
 * WHY a version vector and not a full reactive composite. The kit detail page is
 * served by the `getKit` server action, which composes data Convex CANNOT hold —
 * notably `scanLogs.scannedBy` (a Better Auth USER, which stays in Prisma forever)
 * plus maintenanceRecords/category/location. Replicating that shape in Convex would
 * be infeasible and a data-shape-drift footgun (see CLAUDE.md). Instead we keep the
 * server action byte-identical and add this cheap reactive trigger: the browser
 * subscribes to `version`, and `useReactiveServerQuery` re-runs `getKit` whenever the
 * vector changes. Convex pushes the new vector to EVERY subscriber over the
 * WebSocket → cross-user reactivity, replacing the SSE `kit:updated` invalidation.
 *
 * COVERAGE (the silent-staleness contract — must be a SUPERSET of what the SSE
 * `kit:updated` event covered, i.e. the kit + its direct contents):
 *   • kit doc `updatedAt` — every kit-row mutation (status, notes, name, category,
 *     location, weight, …) bumps Prisma's @updatedAt, which the mirror copies.
 *   • a CONTENT SIGNATURE over each member/media sub-table (NOT just count+max-ts):
 *     a count+timestamp vector would MISS in-place edits like `setKitPrimaryPhoto`
 *     (flips `kitMedia.isPrimary` only → same count, same createdAt) — which changes
 *     the header photo. The signature folds in every mutable, page-visible field, so
 *     add/remove AND in-place edits both change the vector.
 * Cross-domain history the kit page does NOT live-refresh on under the OLD model —
 * project line items (`line-item:changed`), scan logs, maintenance (`maintenance:changed`),
 * and the member assets' own condition (`asset:updated`) — are intentionally NOT in
 * the vector (they emit different SSE events that never invalidated `["kit",…]`), so
 * this stays data-identical, not over-eager.
 *
 * Browser-readable: reads the kit doc, enforces org scoping via requireOrgReadDoc
 * (a user token's orgId must match the kit's org), then reads sub-tables by kitId.
 * Returns only counts/ids/timestamps/flags — no secrets.
 */
export const version = query({
  args: { id: v.string() },
  handler: async (ctx, { id }) => {
    const kit = await ctx.db
      .query("kits")
      .withIndex("by_cuid", (q) => q.eq("id", id))
      .unique();
    await requireOrgReadDoc(ctx, kit);
    if (!kit) return null;

    const [serialized, bulk, media] = await Promise.all([
      ctx.db
        .query("kitSerializedItems")
        .withIndex("by_kitId", (q) => q.eq("kitId", id))
        .collect(),
      ctx.db
        .query("kitBulkItems")
        .withIndex("by_kitId", (q) => q.eq("kitId", id))
        .collect(),
      ctx.db
        .query("kitMedia")
        .withIndex("by_kitId", (q) => q.eq("kitId", id))
        .collect(),
    ]);

    // Deterministic per-row signatures (sorted, so insertion order can't perturb
    // them). Each folds in the mutable fields the detail view renders, so an
    // in-place edit (e.g. isPrimary, position, quantity) changes the vector — not
    // just adds/removes.
    const serializedSig = serialized
      .map((s) => `${s.id}:${s.assetId}:${s.position ?? ""}:${s.sortOrder ?? ""}`)
      .sort()
      .join("|");
    const bulkSig = bulk
      .map(
        (b) =>
          `${b.id}:${b.bulkAssetId}:${b.quantity}:${b.position ?? ""}:${b.sortOrder ?? ""}`,
      )
      .sort()
      .join("|");
    const mediaSig = media
      .map(
        (m) =>
          `${m.id}:${m.isPrimary ? 1 : 0}:${m.sortOrder ?? ""}:${m.type ?? ""}:${m.fileId}:${m.displayName ?? ""}`,
      )
      .sort()
      .join("|");

    return {
      kit: kit.updatedAt ?? kit._creationTime,
      serialized: serializedSig,
      bulk: bulkSig,
      media: mediaSig,
    };
  },
});

/**
 * BROWSER-facing composite for the KIT detail page (Phase 2 native reads). Returns
 * everything getKit needs as RAW docs (members + their assets/models, ≤20 recent
 * usage line items + their projects, ≤20 recent scan logs + their users/projects,
 * media + files, location, category) so the client reconstructs the getKit shape
 * from ONE live subscription. Gated on requireOrgPermission(kit, read).
 *
 * Referenced-only point reads; maintenanceRecords intentionally omitted (the kit
 * page never renders them). Returns null when the kit is missing / cross-org.
 */
async function readKitDetail(ctx: QueryCtx, kitId: string, orgId: string) {
  const kit = await ctx.db.query("kits").withIndex("by_cuid", (q) => q.eq("id", kitId)).unique();
  if (!kit || kit.organizationId !== orgId) return null;

  const [serialized, bulk, lineItemsAll, scanLogsAll, media] = await Promise.all([
    ctx.db.query("kitSerializedItems").withIndex("by_kitId", (q) => q.eq("kitId", kitId)).collect(),
    ctx.db.query("kitBulkItems").withIndex("by_kitId", (q) => q.eq("kitId", kitId)).collect(),
    ctx.db.query("projectLineItems").withIndex("by_kitId", (q) => q.eq("kitId", kitId)).collect(),
    ctx.db.query("assetScanLogs").withIndex("by_kitId", (q) => q.eq("kitId", kitId)).collect(),
    ctx.db.query("kitMedia").withIndex("by_kitId", (q) => q.eq("kitId", kitId)).collect(),
  ]);

  // ≤20 most-recent usage line items + scan logs (mirror getKit's sort + slice).
  const lineItems = [...lineItemsAll]
    .sort((a, b) => (b.createdAt ?? 0) - (a.createdAt ?? 0))
    .slice(0, 20)
    .filter((r) => r.organizationId === orgId);
  const scanLogs = [...scanLogsAll]
    .sort((a, b) => (b.scannedAt ?? 0) - (a.scannedAt ?? 0))
    .slice(0, 20)
    .filter((r) => r.organizationId === orgId);

  const uniq = (arr: Array<string | undefined | null>): string[] => [
    ...new Set(arr.filter((x): x is string => !!x)),
  ];
  const pr = <T>(rows: Promise<T | null>[]) => Promise.all(rows);

  const [assetDocs, bulkDocs] = await Promise.all([
    pr(uniq(serialized.map((s) => s.assetId)).map((id) => ctx.db.query("assets").withIndex("by_cuid", (q) => q.eq("id", id)).unique())),
    pr(uniq(bulk.map((b) => b.bulkAssetId)).map((id) => ctx.db.query("bulkAssets").withIndex("by_cuid", (q) => q.eq("id", id)).unique())),
  ]);
  const inOrg = <T extends { organizationId?: string | null }>(arr: (T | null)[]) =>
    arr.filter((d): d is T => d !== null && d.organizationId === orgId);
  const assets = inOrg(assetDocs);
  const bulkAssets = inOrg(bulkDocs);

  const refModelIds = uniq([...assets.map((a) => a.modelId), ...bulkAssets.map((b) => b.modelId)]);
  const refProjectIds = uniq([...lineItems.map((r) => r.projectId), ...scanLogs.map((r) => r.projectId)]);
  const refUserIds = uniq(scanLogs.map((r) => r.scannedById));
  const refFileIds = uniq(media.map((m) => m.fileId));

  const [modelDocs, projectDocs, userDocs, fileDocs] = await Promise.all([
    pr(refModelIds.map((id) => ctx.db.query("models").withIndex("by_cuid", (q) => q.eq("id", id)).unique())),
    pr(refProjectIds.map((id) => ctx.db.query("projects").withIndex("by_cuid", (q) => q.eq("id", id)).unique())),
    pr(refUserIds.map((id) => ctx.db.query("users").withIndex("by_cuid", (q) => q.eq("id", id)).unique())),
    pr(refFileIds.map((id) => ctx.db.query("fileUploads").withIndex("by_cuid", (q) => q.eq("id", id)).unique())),
  ]);

  const location = kit.locationId
    ? await ctx.db.query("locations").withIndex("by_cuid", (q) => q.eq("id", kit.locationId!)).unique()
    : null;
  const category = kit.categoryId
    ? await ctx.db.query("categories").withIndex("by_cuid", (q) => q.eq("id", kit.categoryId!)).unique()
    : null;

  return {
    kit,
    serializedItems: serialized,
    bulkItems: bulk,
    lineItems,
    scanLogs,
    media,
    assets,
    bulkAssets,
    models: inOrg(modelDocs),
    projects: inOrg(projectDocs),
    users: userDocs.filter((u): u is NonNullable<typeof u> => u !== null),
    files: inOrg(fileDocs),
    location: location && location.organizationId === orgId ? location : null,
    category: category && category.organizationId === orgId ? category : null,
  };
}

export const bundle = query({
  args: { kitId: v.string(), orgId: v.string() },
  handler: async (ctx, { kitId, orgId }) => {
    await requireOrgPermission(ctx, orgId, "kit", "read");
    return readKitDetail(ctx, kitId, orgId);
  },
});
