import { v } from "convex/values";
import { query } from "./_generated/server";
import { requireOrgReadDoc } from "./lib/auth";

/**
 * Reactive "version vector" for the kit DETAIL page (Phase 6 — React Query removal,
 * bucket-B reactive composites). HAND-WRITTEN — NOT generated by
 * scripts/generate-convex-crud.cjs (that script owns convex/kits.ts and would
 * clobber any addition there). Establishes the convex/<table>Detail.ts convention
 * for the other bucket-B detail composites (asset/project/warehouse).
 *
 * WHY a version vector and not a full reactive composite. The kit detail page is
 * served by the `getKit` server action, which composes data Convex CANNOT hold —
 * notably `scanLogs.scannedBy` (a Better Auth USER, which stays in Prisma forever)
 * plus maintenanceRecords/category/location. Replicating that shape in Convex would
 * be infeasible and a data-shape-drift footgun (see CLAUDE.md). Instead we keep the
 * server action byte-identical and add this cheap reactive trigger: the browser
 * subscribes to `version`, and `useReactiveServerQuery` re-runs `getKit` whenever the
 * vector changes. Convex pushes the new vector to EVERY subscriber over the
 * WebSocket → cross-user reactivity, replacing the SSE `kit:updated` invalidation.
 *
 * COVERAGE (the silent-staleness contract — must be a SUPERSET of what the SSE
 * `kit:updated` event covered, i.e. the kit + its direct contents):
 *   • kit doc `updatedAt` — every kit-row mutation (status, notes, name, category,
 *     location, weight, …) bumps Prisma's @updatedAt, which the mirror copies.
 *   • a CONTENT SIGNATURE over each member/media sub-table (NOT just count+max-ts):
 *     a count+timestamp vector would MISS in-place edits like `setKitPrimaryPhoto`
 *     (flips `kitMedia.isPrimary` only → same count, same createdAt) — which changes
 *     the header photo. The signature folds in every mutable, page-visible field, so
 *     add/remove AND in-place edits both change the vector.
 * Cross-domain history the kit page does NOT live-refresh on under the OLD model —
 * project line items (`line-item:changed`), scan logs, maintenance (`maintenance:changed`),
 * and the member assets' own condition (`asset:updated`) — are intentionally NOT in
 * the vector (they emit different SSE events that never invalidated `["kit",…]`), so
 * this stays data-identical, not over-eager.
 *
 * Browser-readable: reads the kit doc, enforces org scoping via requireOrgReadDoc
 * (a user token's orgId must match the kit's org), then reads sub-tables by kitId.
 * Returns only counts/ids/timestamps/flags — no secrets.
 */
export const version = query({
  args: { id: v.string() },
  handler: async (ctx, { id }) => {
    const kit = await ctx.db
      .query("kits")
      .withIndex("by_cuid", (q) => q.eq("id", id))
      .unique();
    await requireOrgReadDoc(ctx, kit);
    if (!kit) return null;

    const [serialized, bulk, media] = await Promise.all([
      ctx.db
        .query("kitSerializedItems")
        .withIndex("by_kitId", (q) => q.eq("kitId", id))
        .collect(),
      ctx.db
        .query("kitBulkItems")
        .withIndex("by_kitId", (q) => q.eq("kitId", id))
        .collect(),
      ctx.db
        .query("kitMedia")
        .withIndex("by_kitId", (q) => q.eq("kitId", id))
        .collect(),
    ]);

    // Deterministic per-row signatures (sorted, so insertion order can't perturb
    // them). Each folds in the mutable fields the detail view renders, so an
    // in-place edit (e.g. isPrimary, position, quantity) changes the vector — not
    // just adds/removes.
    const serializedSig = serialized
      .map((s) => `${s.id}:${s.assetId}:${s.position ?? ""}:${s.sortOrder ?? ""}`)
      .sort()
      .join("|");
    const bulkSig = bulk
      .map(
        (b) =>
          `${b.id}:${b.bulkAssetId}:${b.quantity}:${b.position ?? ""}:${b.sortOrder ?? ""}`,
      )
      .sort()
      .join("|");
    const mediaSig = media
      .map(
        (m) =>
          `${m.id}:${m.isPrimary ? 1 : 0}:${m.sortOrder ?? ""}:${m.type ?? ""}:${m.fileId}:${m.displayName ?? ""}`,
      )
      .sort()
      .join("|");

    return {
      kit: kit.updatedAt ?? kit._creationTime,
      serialized: serializedSig,
      bulk: bulkSig,
      media: mediaSig,
    };
  },
});
