import { v } from "convex/values";
import { query } from "./_generated/server";
import { requireOrgRead, requireOrgReadDoc } from "./lib/auth";

/**
 * Reactive "version vectors" for the WAREHOUSE pages (Phase 6 — React Query
 * removal, bucket-B reactive composites). HAND-WRITTEN — NOT generated by
 * scripts/generate-convex-crud.cjs. Follows the convex/<table>Detail.ts
 * convention from convex/kitDetail.ts + convex/assetDetail.ts.
 *
 * Same migration facts as assetDetail.ts apply: the SSE realtime system currently
 * emits NOTHING (lowercase `entityType` in logActivity vs PascalCase
 * mapEntityTypeToEvent), so `warehouse:changed` never fires and these pages had no
 * cross-user liveness. The version vector is therefore a pure, SAFE ADDITION (it
 * ADDS reactivity), and same-view refresh is preserved by the page's explicit
 * refetch() in each mutation onSuccess.
 *
 * `listVersion` — the warehouse LANDING list (`warehouse/page.tsx`, queryKey
 * ["warehouse-projects", orgId, {search}]). The list renders one card per project
 * whose status is in the warehouse pipeline (CONFIRMED → PREPPING → CHECKED_OUT →
 * ON_SITE → RETURNED), grouped by rental-start urgency. The reactive surface is
 * the project rows themselves: a card shows status + name + client + date range,
 * and a project ENTERS/LEAVES the list when its status crosses the pipeline
 * boundary. So the vector is a content signature over the org's pipeline-status,
 * non-template projects, folding in every field the list renders or filters on
 * (status / rentalStartDate / rentalEndDate / clientId) plus updatedAt.
 *
 * Membership transitions move the vector for free: QUOTE→CONFIRMED adds a signed
 * row (project appears), RETURNED→COMPLETED drops it (project disappears). A
 * change between two non-pipeline statuses doesn't move it — correct, it's not on
 * this list. projects + projectLineItems are both dual-written, so this is live.
 *
 * KNOWN SCOPE NOTE: line-item-level changes that do NOT change project.status are
 * intentionally OUT of this list vector — the cards don't render line-item
 * progress, and the only place the list reads line items is the
 * deploy/return confirmation dialog's warning count (point-in-time, low stakes,
 * re-read from the loaded data). The per-project DETAIL page
 * (warehouse/[projectId]) is where line-item reactivity belongs — see the
 * handoff note in FEATUREDOCS/54 for the `version({projectId})` query that watches
 * projectLineItems for that page (not yet built).
 *
 * Browser-readable: org-scoped via requireOrgRead(orgId); returns only
 * counts/ids/status/timestamps — no secrets.
 */

// Mirrors WAREHOUSE_STATUSES in src/app/(app)/warehouse/page.tsx — the project
// statuses the warehouse landing list renders.
const WAREHOUSE_STATUSES = new Set([
  "CONFIRMED",
  "PREPPING",
  "CHECKED_OUT",
  "ON_SITE",
  "RETURNED",
]);

export const listVersion = query({
  args: { orgId: v.string() },
  handler: async (ctx, { orgId }) => {
    await requireOrgRead(ctx, orgId);

    const projects = await ctx.db
      .query("projects")
      .withIndex("by_organizationId", (q) => q.eq("organizationId", orgId))
      .collect();

    const pipeline = projects.filter(
      (p) => p.isTemplate !== true && WAREHOUSE_STATUSES.has(p.status ?? ""),
    );

    // getProjects' dependencies beyond the project row are TWO cross-domain joins
    // that don't touch the project row when they change (so project.updatedAt won't
    // move): the displayed `client.name`, and `location.name` which getProjects'
    // SEARCH matches on (`OR: [{ name }, { projectNumber }, { location: { name } }]`).
    // project.name/projectNumber ARE on the project row → covered by updatedAt. Both
    // clients and locations are dual-written, so fold their names in — else a
    // cross-user client/location rename leaves the (possibly search-filtered) list
    // stale until a separate project change (codex review, both flagged P2). This
    // CLOSES the getProjects dependency set; resolve only the distinct ids referenced.
    const resolveNames = async (table: "clients" | "locations", ids: (string | undefined)[]) => {
      const unique = [...new Set(ids.filter(Boolean) as string[])];
      const docs = await Promise.all(
        unique.map((id) =>
          ctx.db.query(table).withIndex("by_cuid", (q) => q.eq("id", id)).unique(),
        ),
      );
      return new Map(docs.filter(Boolean).map((d) => [d!.id, d!.name ?? ""]));
    };
    const [clientName, locationName] = await Promise.all([
      resolveNames("clients", pipeline.map((p) => p.clientId)),
      resolveNames("locations", pipeline.map((p) => p.locationId)),
    ]);

    const sig = pipeline
      .map(
        (p) =>
          `${p.id}:${p.status ?? ""}:${p.rentalStartDate ?? ""}:${p.rentalEndDate ?? ""}:${p.clientId ?? ""}:${p.clientId ? (clientName.get(p.clientId) ?? "") : ""}:${p.locationId ? (locationName.get(p.locationId) ?? "") : ""}:${p.updatedAt ?? p._creationTime}`,
      )
      .sort()
      .join("|");

    return { projects: sig };
  },
});

/**
 * `version` — the per-project WAREHOUSE DETAIL composite
 * (`warehouse/[projectId]/page.tsx`, queryKey ["warehouse-project", orgId,
 * projectId]). The cheap reactive value `useReactiveServerQuery` watches to
 * re-run the unchanged `getProjectForWarehouse` server action whenever any
 * warehouse-visible field of the project or its line items changes — cross-user
 * over the WebSocket, replacing the (currently dead) SSE `warehouse-project`
 * invalidation. Establishes nothing new beyond the kitDetail/assetDetail
 * convention; see those files for the version-vector rationale.
 *
 * COVERAGE (the silent-staleness contract — must be a superset of the page's
 * mutable, mirror-backed surface):
 *   • project doc `updatedAt` + `status` — the header (status pill / name /
 *     number, all on the project row → bumped by @updatedAt) and pipeline
 *     transitions.
 *   • `client` name — the header renders `project.client.name`; a client rename
 *     does NOT touch the project row, so project.updatedAt won't move (same
 *     cross-domain-join-freshness class codex flagged on `listVersion`). Clients
 *     are dual-written, so fold the resolved name in.
 *   • a CONTENT SIGNATURE over the project's `projectLineItems` (by_projectId),
 *     folding every mutable warehouse-visible rollup the Pick/Prep · Deploy ·
 *     Return · Bulk-Check-In · Close-Out tabs render or flip IN PLACE: status,
 *     prepStatus, prepContainer, the quantity rollups (quantity /
 *     checkedOutQuantity / returnedQuantity / assigned / packed / damaged /
 *     lost), the asset/bulk/kit assignment, return condition/status, and the
 *     checkout/return timestamps. An in-place check-out (a line-item status +
 *     checkedOutQuantity flip at the SAME row count) moves the signature — the
 *     proof the round-trip script asserts.
 *
 * KNOWN SCOPE NOTE: the per-unit `project_line_item_unit` fulfillment rows are
 * NOT dual-written to Convex (the line-item mirror strips `units`), so the vector
 * watches the line-item ROLLUPS instead — every warehouse mutation updates those
 * rollups in the same `$transaction` and re-mirrors all of the project's line
 * items via `upsertProjectLineItemsToConvex`, so a rollup-level signature tracks
 * the unit flips it summarises. The page's own per-mutation `refetch()` covers
 * same-view freshness independently of this vector regardless (the SSE path emits
 * nothing today — see assetDetail.ts — so this vector is a pure additive
 * cross-user improvement, not a data-identical contract that could regress).
 *
 * Browser-readable: reads the project doc, enforces org scoping via
 * requireOrgReadDoc, then reads line items by projectId. Returns only
 * ids/status/quantities/timestamps — no secrets.
 */
export const version = query({
  args: { projectId: v.string() },
  handler: async (ctx, { projectId }) => {
    const project = await ctx.db
      .query("projects")
      .withIndex("by_cuid", (q) => q.eq("id", projectId))
      .unique();
    await requireOrgReadDoc(ctx, project);
    if (!project) return null;

    const lineItems = await ctx.db
      .query("projectLineItems")
      .withIndex("by_projectId", (q) => q.eq("projectId", projectId))
      .collect();

    // Deterministic per-row signature (sorted, so mirror insertion order can't
    // perturb it). Folds every mutable warehouse-visible rollup so an add/remove
    // AND an in-place status/quantity flip both move the vector.
    const lineItemsSig = lineItems
      .map(
        (li) =>
          `${li.id}:${li.status ?? ""}:${li.prepStatus ?? ""}:${li.prepContainer ?? ""}:${li.quantity ?? ""}:${li.checkedOutQuantity ?? ""}:${li.returnedQuantity ?? ""}:${li.assignedQuantity ?? ""}:${li.packedQuantity ?? ""}:${li.damagedQuantity ?? ""}:${li.lostQuantity ?? ""}:${li.assetId ?? ""}:${li.bulkAssetId ?? ""}:${li.kitId ?? ""}:${li.returnCondition ?? ""}:${li.returnStatus ?? ""}:${li.checkedOutAt ?? ""}:${li.returnedAt ?? ""}:${li.updatedAt ?? li._creationTime}`,
      )
      .sort()
      .join("|");

    const clientName = project.clientId
      ? ((
          await ctx.db
            .query("clients")
            .withIndex("by_cuid", (q) => q.eq("id", project.clientId!))
            .unique()
        )?.name ?? "")
      : "";

    return {
      project: project.updatedAt ?? project._creationTime,
      status: project.status ?? "",
      client: clientName,
      lineItems: lineItemsSig,
    };
  },
});
