import { v } from "convex/values";
import { query } from "./_generated/server";
import { requireOrgRead } from "./lib/auth";

/**
 * Reactive "version vectors" for the WAREHOUSE pages (Phase 6 — React Query
 * removal, bucket-B reactive composites). HAND-WRITTEN — NOT generated by
 * scripts/generate-convex-crud.cjs. Follows the convex/<table>Detail.ts
 * convention from convex/kitDetail.ts + convex/assetDetail.ts.
 *
 * Same migration facts as assetDetail.ts apply: the SSE realtime system currently
 * emits NOTHING (lowercase `entityType` in logActivity vs PascalCase
 * mapEntityTypeToEvent), so `warehouse:changed` never fires and these pages had no
 * cross-user liveness. The version vector is therefore a pure, SAFE ADDITION (it
 * ADDS reactivity), and same-view refresh is preserved by the page's explicit
 * refetch() in each mutation onSuccess.
 *
 * `listVersion` — the warehouse LANDING list (`warehouse/page.tsx`, queryKey
 * ["warehouse-projects", orgId, {search}]). The list renders one card per project
 * whose status is in the warehouse pipeline (CONFIRMED → PREPPING → CHECKED_OUT →
 * ON_SITE → RETURNED), grouped by rental-start urgency. The reactive surface is
 * the project rows themselves: a card shows status + name + client + date range,
 * and a project ENTERS/LEAVES the list when its status crosses the pipeline
 * boundary. So the vector is a content signature over the org's pipeline-status,
 * non-template projects, folding in every field the list renders or filters on
 * (status / rentalStartDate / rentalEndDate / clientId) plus updatedAt.
 *
 * Membership transitions move the vector for free: QUOTE→CONFIRMED adds a signed
 * row (project appears), RETURNED→COMPLETED drops it (project disappears). A
 * change between two non-pipeline statuses doesn't move it — correct, it's not on
 * this list. projects + projectLineItems are both dual-written, so this is live.
 *
 * KNOWN SCOPE NOTE: line-item-level changes that do NOT change project.status are
 * intentionally OUT of this list vector — the cards don't render line-item
 * progress, and the only place the list reads line items is the
 * deploy/return confirmation dialog's warning count (point-in-time, low stakes,
 * re-read from the loaded data). The per-project DETAIL page
 * (warehouse/[projectId]) is where line-item reactivity belongs — see the
 * handoff note in FEATUREDOCS/54 for the `version({projectId})` query that watches
 * projectLineItems for that page (not yet built).
 *
 * Browser-readable: org-scoped via requireOrgRead(orgId); returns only
 * counts/ids/status/timestamps — no secrets.
 */

// Mirrors WAREHOUSE_STATUSES in src/app/(app)/warehouse/page.tsx — the project
// statuses the warehouse landing list renders.
const WAREHOUSE_STATUSES = new Set([
  "CONFIRMED",
  "PREPPING",
  "CHECKED_OUT",
  "ON_SITE",
  "RETURNED",
]);

export const listVersion = query({
  args: { orgId: v.string() },
  handler: async (ctx, { orgId }) => {
    await requireOrgRead(ctx, orgId);

    const projects = await ctx.db
      .query("projects")
      .withIndex("by_organizationId", (q) => q.eq("organizationId", orgId))
      .collect();

    const pipeline = projects.filter(
      (p) => p.isTemplate !== true && WAREHOUSE_STATUSES.has(p.status ?? ""),
    );

    // The card renders `project.client.name` (a cross-domain join in getProjects),
    // and clients are dual-written to Convex but a client rename does NOT touch the
    // project row — so fold the referenced clients' name into the signature, or a
    // cross-user rename would leave the card stale until a separate project change
    // (codex review). Resolve only the distinct clientIds the pipeline references.
    const clientIds = [...new Set(pipeline.map((p) => p.clientId).filter(Boolean) as string[])];
    const clientDocs = await Promise.all(
      clientIds.map((id) =>
        ctx.db.query("clients").withIndex("by_cuid", (q) => q.eq("id", id)).unique(),
      ),
    );
    const clientName = new Map(clientDocs.filter(Boolean).map((c) => [c!.id, c!.name ?? ""]));

    const sig = pipeline
      .map(
        (p) =>
          `${p.id}:${p.status ?? ""}:${p.rentalStartDate ?? ""}:${p.rentalEndDate ?? ""}:${p.clientId ?? ""}:${p.clientId ? (clientName.get(p.clientId) ?? "") : ""}:${p.updatedAt ?? p._creationTime}`,
      )
      .sort()
      .join("|");

    return { projects: sig };
  },
});
