/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as activityLog from "../activityLog.js";
import type * as activityLogWrites from "../activityLogWrites.js";
import type * as apiKeys from "../apiKeys.js";
import type * as assetAccessories from "../assetAccessories.js";
import type * as assetAccessoriesWrites from "../assetAccessoriesWrites.js";
import type * as assetBulkChildren from "../assetBulkChildren.js";
import type * as assetDetail from "../assetDetail.js";
import type * as assetMedia from "../assetMedia.js";
import type * as assetScanLogs from "../assetScanLogs.js";
import type * as assetWrites from "../assetWrites.js";
import type * as assets from "../assets.js";
import type * as availability from "../availability.js";
import type * as availabilityCheck from "../availabilityCheck.js";
import type * as backfillKitUnits from "../backfillKitUnits.js";
import type * as brandTemplates from "../brandTemplates.js";
import type * as bulkAssets from "../bulkAssets.js";
import type * as bulkAssetsWrites from "../bulkAssetsWrites.js";
import type * as categories from "../categories.js";
import type * as categoriesWrites from "../categoriesWrites.js";
import type * as categorySlots from "../categorySlots.js";
import type * as categorySlotsWrites from "../categorySlotsWrites.js";
import type * as checkItems from "../checkItems.js";
import type * as checkItemsWrites from "../checkItemsWrites.js";
import type * as checkRecordOps from "../checkRecordOps.js";
import type * as checkRecordWrites from "../checkRecordWrites.js";
import type * as checkRecords from "../checkRecords.js";
import type * as clientMedia from "../clientMedia.js";
import type * as clientWrites from "../clientWrites.js";
import type * as clients from "../clients.js";
import type * as collaboration from "../collaboration.js";
import type * as crew from "../crew.js";
import type * as crewAssignments from "../crewAssignments.js";
import type * as crewAssignmentsWrites from "../crewAssignmentsWrites.js";
import type * as crewAvailabilities from "../crewAvailabilities.js";
import type * as crewAvailability from "../crewAvailability.js";
import type * as crewAvailabilityWrites from "../crewAvailabilityWrites.js";
import type * as crewDashboard from "../crewDashboard.js";
import type * as crewMembers from "../crewMembers.js";
import type * as crewRoles from "../crewRoles.js";
import type * as crewShifts from "../crewShifts.js";
import type * as crewSkills from "../crewSkills.js";
import type * as crewTimeEntries from "../crewTimeEntries.js";
import type * as crewTimeEntriesWrites from "../crewTimeEntriesWrites.js";
import type * as crewWrites from "../crewWrites.js";
import type * as crons from "../crons.js";
import type * as customFieldDefinitions from "../customFieldDefinitions.js";
import type * as customFieldDefinitionsWrites from "../customFieldDefinitionsWrites.js";
import type * as dashboardActivity from "../dashboardActivity.js";
import type * as dashboardCounters from "../dashboardCounters.js";
import type * as dashboardLists from "../dashboardLists.js";
import type * as dashboardStats from "../dashboardStats.js";
import type * as dashboardSubHire from "../dashboardSubHire.js";
import type * as documentTemplates from "../documentTemplates.js";
import type * as emailActions from "../emailActions.js";
import type * as emails from "../emails.js";
import type * as equipmentTab from "../equipmentTab.js";
import type * as fileUploads from "../fileUploads.js";
import type * as files from "../files.js";
import type * as globalSearch from "../globalSearch.js";
import type * as groupTemplateItems from "../groupTemplateItems.js";
import type * as groupTemplates from "../groupTemplates.js";
import type * as groupTemplatesWrites from "../groupTemplatesWrites.js";
import type * as http from "../http.js";
import type * as kitAllocations from "../kitAllocations.js";
import type * as kitAllocationsWrites from "../kitAllocationsWrites.js";
import type * as kitBulkItems from "../kitBulkItems.js";
import type * as kitCheckItems from "../kitCheckItems.js";
import type * as kitDetail from "../kitDetail.js";
import type * as kitMedia from "../kitMedia.js";
import type * as kitSerializedItems from "../kitSerializedItems.js";
import type * as kitWrites from "../kitWrites.js";
import type * as kits from "../kits.js";
import type * as lib_allocation from "../lib/allocation.js";
import type * as lib_assetTagCounter from "../lib/assetTagCounter.js";
import type * as lib_audit from "../lib/audit.js";
import type * as lib_auditChanges from "../lib/auditChanges.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_availabilityBookings from "../lib/availabilityBookings.js";
import type * as lib_availabilityCore from "../lib/availabilityCore.js";
import type * as lib_blockingCommentsGate from "../lib/blockingCommentsGate.js";
import type * as lib_bulkCheckin from "../lib/bulkCheckin.js";
import type * as lib_checkPredictiveMaintenanceCore from "../lib/checkPredictiveMaintenanceCore.js";
import type * as lib_collaborationColors from "../lib/collaborationColors.js";
import type * as lib_counters from "../lib/counters.js";
import type * as lib_crewRate from "../lib/crewRate.js";
import type * as lib_crewTimeHours from "../lib/crewTimeHours.js";
import type * as lib_dto from "../lib/dto.js";
import type * as lib_fulfillment from "../lib/fulfillment.js";
import type * as lib_inventory from "../lib/inventory.js";
import type * as lib_lineItemUnits from "../lib/lineItemUnits.js";
import type * as lib_moneyGuards from "../lib/moneyGuards.js";
import type * as lib_notificationPreferences from "../lib/notificationPreferences.js";
import type * as lib_permissionsCore from "../lib/permissionsCore.js";
import type * as lib_projectNumber from "../lib/projectNumber.js";
import type * as lib_projectNumberCounter from "../lib/projectNumberCounter.js";
import type * as lib_rateLimiter from "../lib/rateLimiter.js";
import type * as lib_recalc from "../lib/recalc.js";
import type * as lib_reservationConflicts from "../lib/reservationConflicts.js";
import type * as lib_sanitizeSet from "../lib/sanitizeSet.js";
import type * as lib_searchScore from "../lib/searchScore.js";
import type * as lib_shardedCounter from "../lib/shardedCounter.js";
import type * as lib_subHireLineGen from "../lib/subHireLineGen.js";
import type * as lib_subHireOrderCounter from "../lib/subHireOrderCounter.js";
import type * as lib_subHireTotals from "../lib/subHireTotals.js";
import type * as lib_suggestedPrice from "../lib/suggestedPrice.js";
import type * as lib_testTagIdCounter from "../lib/testTagIdCounter.js";
import type * as lib_testtag from "../lib/testtag.js";
import type * as lib_testtagBackfill from "../lib/testtagBackfill.js";
import type * as lib_validators from "../lib/validators.js";
import type * as lib_webhookEnqueue from "../lib/webhookEnqueue.js";
import type * as lib_writeGuard from "../lib/writeGuard.js";
import type * as lineItemMergeMaps from "../lineItemMergeMaps.js";
import type * as lineItemWrites from "../lineItemWrites.js";
import type * as locationMedia from "../locationMedia.js";
import type * as locations from "../locations.js";
import type * as locationsWrites from "../locationsWrites.js";
import type * as maintenanceRecordAssets from "../maintenanceRecordAssets.js";
import type * as maintenanceRecords from "../maintenanceRecords.js";
import type * as maintenanceWrites from "../maintenanceWrites.js";
import type * as mediaWrites from "../mediaWrites.js";
import type * as members from "../members.js";
import type * as modelBulkAccessories from "../modelBulkAccessories.js";
import type * as modelBulkAccessoriesWrites from "../modelBulkAccessoriesWrites.js";
import type * as modelCheckItems from "../modelCheckItems.js";
import type * as modelMedia from "../modelMedia.js";
import type * as modelWrites from "../modelWrites.js";
import type * as models from "../models.js";
import type * as notificationDismissals from "../notificationDismissals.js";
import type * as notificationDismissalsWrites from "../notificationDismissalsWrites.js";
import type * as notificationEmailLogs from "../notificationEmailLogs.js";
import type * as orgExport from "../orgExport.js";
import type * as orgSettings from "../orgSettings.js";
import type * as overbooking from "../overbooking.js";
import type * as parity from "../parity.js";
import type * as pendingSSOApprovals from "../pendingSSOApprovals.js";
import type * as projectCategories from "../projectCategories.js";
import type * as projectCategoriesWrites from "../projectCategoriesWrites.js";
import type * as projectCosts from "../projectCosts.js";
import type * as projectDetail from "../projectDetail.js";
import type * as projectEquipment from "../projectEquipment.js";
import type * as projectGroups from "../projectGroups.js";
import type * as projectGroupsWrites from "../projectGroupsWrites.js";
import type * as projectLineItemUnits from "../projectLineItemUnits.js";
import type * as projectLineItems from "../projectLineItems.js";
import type * as projectManagers from "../projectManagers.js";
import type * as projectManagersWrites from "../projectManagersWrites.js";
import type * as projectMedia from "../projectMedia.js";
import type * as projectNumberSequences from "../projectNumberSequences.js";
import type * as projectServices from "../projectServices.js";
import type * as projectServicesWrites from "../projectServicesWrites.js";
import type * as projectTasks from "../projectTasks.js";
import type * as projectTasksWrites from "../projectTasksWrites.js";
import type * as projectWrites from "../projectWrites.js";
import type * as projects from "../projects.js";
import type * as purgeRemovedTables from "../purgeRemovedTables.js";
import type * as reservationConflicts from "../reservationConflicts.js";
import type * as revenueAllocation from "../revenueAllocation.js";
import type * as roi from "../roi.js";
import type * as savedTableViews from "../savedTableViews.js";
import type * as savedTableViewsWrites from "../savedTableViewsWrites.js";
import type * as scanLookup from "../scanLookup.js";
import type * as scheduledJobs from "../scheduledJobs.js";
import type * as search from "../search.js";
import type * as sectionPresets from "../sectionPresets.js";
import type * as serviceTemplates from "../serviceTemplates.js";
import type * as siteSettings from "../siteSettings.js";
import type * as subHireGroups from "../subHireGroups.js";
import type * as subHireItems from "../subHireItems.js";
import type * as subHireMedia from "../subHireMedia.js";
import type * as subHires from "../subHires.js";
import type * as subHiresWrites from "../subHiresWrites.js";
import type * as subTestRecords from "../subTestRecords.js";
import type * as supplierModelRates from "../supplierModelRates.js";
import type * as supplierOrderItems from "../supplierOrderItems.js";
import type * as supplierOrders from "../supplierOrders.js";
import type * as supplierOrdersWrites from "../supplierOrdersWrites.js";
import type * as suppliers from "../suppliers.js";
import type * as suppliersWrites from "../suppliersWrites.js";
import type * as systemFlags from "../systemFlags.js";
import type * as tags from "../tags.js";
import type * as testProfiles from "../testProfiles.js";
import type * as testProfilesWrites from "../testProfilesWrites.js";
import type * as testTagAssets from "../testTagAssets.js";
import type * as testTagAssetsWrites from "../testTagAssetsWrites.js";
import type * as testTagAuditorTokens from "../testTagAuditorTokens.js";
import type * as testTagRecords from "../testTagRecords.js";
import type * as testTagRecordsWrites from "../testTagRecordsWrites.js";
import type * as userNotificationPreferences from "../userNotificationPreferences.js";
import type * as users from "../users.js";
import type * as warehouseCloseWrites from "../warehouseCloseWrites.js";
import type * as warehouseCloses from "../warehouseCloses.js";
import type * as warehouseDashboardTokens from "../warehouseDashboardTokens.js";
import type * as warehouseDetail from "../warehouseDetail.js";
import type * as warehouseList from "../warehouseList.js";
import type * as warehouseOps from "../warehouseOps.js";
import type * as warehouseWrites from "../warehouseWrites.js";
import type * as webhooks from "../webhooks.js";
import type * as wooCommerceActions from "../wooCommerceActions.js";
import type * as wooCommerceIntegrations from "../wooCommerceIntegrations.js";
import type * as wooCommerceInternal from "../wooCommerceInternal.js";
import type * as wooCommerceOrderLogs from "../wooCommerceOrderLogs.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  activityLog: typeof activityLog;
  activityLogWrites: typeof activityLogWrites;
  apiKeys: typeof apiKeys;
  assetAccessories: typeof assetAccessories;
  assetAccessoriesWrites: typeof assetAccessoriesWrites;
  assetBulkChildren: typeof assetBulkChildren;
  assetDetail: typeof assetDetail;
  assetMedia: typeof assetMedia;
  assetScanLogs: typeof assetScanLogs;
  assetWrites: typeof assetWrites;
  assets: typeof assets;
  availability: typeof availability;
  availabilityCheck: typeof availabilityCheck;
  backfillKitUnits: typeof backfillKitUnits;
  brandTemplates: typeof brandTemplates;
  bulkAssets: typeof bulkAssets;
  bulkAssetsWrites: typeof bulkAssetsWrites;
  categories: typeof categories;
  categoriesWrites: typeof categoriesWrites;
  categorySlots: typeof categorySlots;
  categorySlotsWrites: typeof categorySlotsWrites;
  checkItems: typeof checkItems;
  checkItemsWrites: typeof checkItemsWrites;
  checkRecordOps: typeof checkRecordOps;
  checkRecordWrites: typeof checkRecordWrites;
  checkRecords: typeof checkRecords;
  clientMedia: typeof clientMedia;
  clientWrites: typeof clientWrites;
  clients: typeof clients;
  collaboration: typeof collaboration;
  crew: typeof crew;
  crewAssignments: typeof crewAssignments;
  crewAssignmentsWrites: typeof crewAssignmentsWrites;
  crewAvailabilities: typeof crewAvailabilities;
  crewAvailability: typeof crewAvailability;
  crewAvailabilityWrites: typeof crewAvailabilityWrites;
  crewDashboard: typeof crewDashboard;
  crewMembers: typeof crewMembers;
  crewRoles: typeof crewRoles;
  crewShifts: typeof crewShifts;
  crewSkills: typeof crewSkills;
  crewTimeEntries: typeof crewTimeEntries;
  crewTimeEntriesWrites: typeof crewTimeEntriesWrites;
  crewWrites: typeof crewWrites;
  crons: typeof crons;
  customFieldDefinitions: typeof customFieldDefinitions;
  customFieldDefinitionsWrites: typeof customFieldDefinitionsWrites;
  dashboardActivity: typeof dashboardActivity;
  dashboardCounters: typeof dashboardCounters;
  dashboardLists: typeof dashboardLists;
  dashboardStats: typeof dashboardStats;
  dashboardSubHire: typeof dashboardSubHire;
  documentTemplates: typeof documentTemplates;
  emailActions: typeof emailActions;
  emails: typeof emails;
  equipmentTab: typeof equipmentTab;
  fileUploads: typeof fileUploads;
  files: typeof files;
  globalSearch: typeof globalSearch;
  groupTemplateItems: typeof groupTemplateItems;
  groupTemplates: typeof groupTemplates;
  groupTemplatesWrites: typeof groupTemplatesWrites;
  http: typeof http;
  kitAllocations: typeof kitAllocations;
  kitAllocationsWrites: typeof kitAllocationsWrites;
  kitBulkItems: typeof kitBulkItems;
  kitCheckItems: typeof kitCheckItems;
  kitDetail: typeof kitDetail;
  kitMedia: typeof kitMedia;
  kitSerializedItems: typeof kitSerializedItems;
  kitWrites: typeof kitWrites;
  kits: typeof kits;
  "lib/allocation": typeof lib_allocation;
  "lib/assetTagCounter": typeof lib_assetTagCounter;
  "lib/audit": typeof lib_audit;
  "lib/auditChanges": typeof lib_auditChanges;
  "lib/auth": typeof lib_auth;
  "lib/availabilityBookings": typeof lib_availabilityBookings;
  "lib/availabilityCore": typeof lib_availabilityCore;
  "lib/blockingCommentsGate": typeof lib_blockingCommentsGate;
  "lib/bulkCheckin": typeof lib_bulkCheckin;
  "lib/checkPredictiveMaintenanceCore": typeof lib_checkPredictiveMaintenanceCore;
  "lib/collaborationColors": typeof lib_collaborationColors;
  "lib/counters": typeof lib_counters;
  "lib/crewRate": typeof lib_crewRate;
  "lib/crewTimeHours": typeof lib_crewTimeHours;
  "lib/dto": typeof lib_dto;
  "lib/fulfillment": typeof lib_fulfillment;
  "lib/inventory": typeof lib_inventory;
  "lib/lineItemUnits": typeof lib_lineItemUnits;
  "lib/moneyGuards": typeof lib_moneyGuards;
  "lib/notificationPreferences": typeof lib_notificationPreferences;
  "lib/permissionsCore": typeof lib_permissionsCore;
  "lib/projectNumber": typeof lib_projectNumber;
  "lib/projectNumberCounter": typeof lib_projectNumberCounter;
  "lib/rateLimiter": typeof lib_rateLimiter;
  "lib/recalc": typeof lib_recalc;
  "lib/reservationConflicts": typeof lib_reservationConflicts;
  "lib/sanitizeSet": typeof lib_sanitizeSet;
  "lib/searchScore": typeof lib_searchScore;
  "lib/shardedCounter": typeof lib_shardedCounter;
  "lib/subHireLineGen": typeof lib_subHireLineGen;
  "lib/subHireOrderCounter": typeof lib_subHireOrderCounter;
  "lib/subHireTotals": typeof lib_subHireTotals;
  "lib/suggestedPrice": typeof lib_suggestedPrice;
  "lib/testTagIdCounter": typeof lib_testTagIdCounter;
  "lib/testtag": typeof lib_testtag;
  "lib/testtagBackfill": typeof lib_testtagBackfill;
  "lib/validators": typeof lib_validators;
  "lib/webhookEnqueue": typeof lib_webhookEnqueue;
  "lib/writeGuard": typeof lib_writeGuard;
  lineItemMergeMaps: typeof lineItemMergeMaps;
  lineItemWrites: typeof lineItemWrites;
  locationMedia: typeof locationMedia;
  locations: typeof locations;
  locationsWrites: typeof locationsWrites;
  maintenanceRecordAssets: typeof maintenanceRecordAssets;
  maintenanceRecords: typeof maintenanceRecords;
  maintenanceWrites: typeof maintenanceWrites;
  mediaWrites: typeof mediaWrites;
  members: typeof members;
  modelBulkAccessories: typeof modelBulkAccessories;
  modelBulkAccessoriesWrites: typeof modelBulkAccessoriesWrites;
  modelCheckItems: typeof modelCheckItems;
  modelMedia: typeof modelMedia;
  modelWrites: typeof modelWrites;
  models: typeof models;
  notificationDismissals: typeof notificationDismissals;
  notificationDismissalsWrites: typeof notificationDismissalsWrites;
  notificationEmailLogs: typeof notificationEmailLogs;
  orgExport: typeof orgExport;
  orgSettings: typeof orgSettings;
  overbooking: typeof overbooking;
  parity: typeof parity;
  pendingSSOApprovals: typeof pendingSSOApprovals;
  projectCategories: typeof projectCategories;
  projectCategoriesWrites: typeof projectCategoriesWrites;
  projectCosts: typeof projectCosts;
  projectDetail: typeof projectDetail;
  projectEquipment: typeof projectEquipment;
  projectGroups: typeof projectGroups;
  projectGroupsWrites: typeof projectGroupsWrites;
  projectLineItemUnits: typeof projectLineItemUnits;
  projectLineItems: typeof projectLineItems;
  projectManagers: typeof projectManagers;
  projectManagersWrites: typeof projectManagersWrites;
  projectMedia: typeof projectMedia;
  projectNumberSequences: typeof projectNumberSequences;
  projectServices: typeof projectServices;
  projectServicesWrites: typeof projectServicesWrites;
  projectTasks: typeof projectTasks;
  projectTasksWrites: typeof projectTasksWrites;
  projectWrites: typeof projectWrites;
  projects: typeof projects;
  purgeRemovedTables: typeof purgeRemovedTables;
  reservationConflicts: typeof reservationConflicts;
  revenueAllocation: typeof revenueAllocation;
  roi: typeof roi;
  savedTableViews: typeof savedTableViews;
  savedTableViewsWrites: typeof savedTableViewsWrites;
  scanLookup: typeof scanLookup;
  scheduledJobs: typeof scheduledJobs;
  search: typeof search;
  sectionPresets: typeof sectionPresets;
  serviceTemplates: typeof serviceTemplates;
  siteSettings: typeof siteSettings;
  subHireGroups: typeof subHireGroups;
  subHireItems: typeof subHireItems;
  subHireMedia: typeof subHireMedia;
  subHires: typeof subHires;
  subHiresWrites: typeof subHiresWrites;
  subTestRecords: typeof subTestRecords;
  supplierModelRates: typeof supplierModelRates;
  supplierOrderItems: typeof supplierOrderItems;
  supplierOrders: typeof supplierOrders;
  supplierOrdersWrites: typeof supplierOrdersWrites;
  suppliers: typeof suppliers;
  suppliersWrites: typeof suppliersWrites;
  systemFlags: typeof systemFlags;
  tags: typeof tags;
  testProfiles: typeof testProfiles;
  testProfilesWrites: typeof testProfilesWrites;
  testTagAssets: typeof testTagAssets;
  testTagAssetsWrites: typeof testTagAssetsWrites;
  testTagAuditorTokens: typeof testTagAuditorTokens;
  testTagRecords: typeof testTagRecords;
  testTagRecordsWrites: typeof testTagRecordsWrites;
  userNotificationPreferences: typeof userNotificationPreferences;
  users: typeof users;
  warehouseCloseWrites: typeof warehouseCloseWrites;
  warehouseCloses: typeof warehouseCloses;
  warehouseDashboardTokens: typeof warehouseDashboardTokens;
  warehouseDetail: typeof warehouseDetail;
  warehouseList: typeof warehouseList;
  warehouseOps: typeof warehouseOps;
  warehouseWrites: typeof warehouseWrites;
  webhooks: typeof webhooks;
  wooCommerceActions: typeof wooCommerceActions;
  wooCommerceIntegrations: typeof wooCommerceIntegrations;
  wooCommerceInternal: typeof wooCommerceInternal;
  wooCommerceOrderLogs: typeof wooCommerceOrderLogs;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  shardedCounter: import("@convex-dev/sharded-counter/_generated/component.js").ComponentApi<"shardedCounter">;
};
